language: python
dist: trusty
sudo: required

branches:
  # prevent bors temporary branches to be built
  except:
  - staging.tmp
  - trying.tmp

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  - PANDAS_VERSION=0.24
  #- PANDAS_VERSION=0.25

install:
  - pip install --upgrade pip
  - pip install --upgrade pytest  # pre installed version too old
  - pip install pandas==$PANDAS_VERSION
  - pip install -e .[test]

script:
  - python -m coverage run -p --source=pintpandas --omit="*test*","*compat*" -m py.test -rfsxEX
  # only test notebooks using the same setup as was used to run the notebook originally. pandas prints repr different in 0.24/0.25.
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 && $PANDAS_VERSION == 0.24 ]]; then python -m pytest --nbval notebooks; fi
  - coverage combine
  - coverage report -m

after_success:
  - coveralls --verbose
